# ------------------------------------------------------------------------------
# Code to render all figures included in the paper
# (Figure 1 is generated by separate tex files)
#
# See LICENSE file for copyright
# ------------------------------------------------------------------------------

# --- Source relevant code -----------------------------------------------------

source("code/utils.R")
for (exp in EXPERIMENTS) {
  get(glue("{exp}_read_exp_data"))()
  source(glue("code/{exp}_create_result_objects.R"))
} 

export_figure <- function(
    p, fname, format = "pdf", width = 6, height = 4, ...
) {
  ggsave(
    paste0("output/", fname, ".", format), 
    p, width = width, height = height, ...
  )
}

showtext_auto()

# --- Honesty Experiment -------------------------------------------------------

p <- honesty_fig_by_period() +
  theme(text = element_text(family = "Times New Roman"))
export_figure(p, "figure2_honesty_pct_honest")


# --- Gift Exchange Experiment -------------------------------------------------

p <- giftex_fig_wage_effort()  +
  theme(text = element_text(family = "Times New Roman"))
export_figure(p, "figure3_giftex_effort_on_wage", height = 6)


# --- Trust Experiment ---------------------------------------------------------

p <- trust_fig_inv_by_period()  +
  theme(text = element_text(family = "Times New Roman"))
export_figure(p, "figure4_trust_investment")