---
title: "accframe - Qualitative Analysis"
format: pdf
execute: 
  warning: false
  message: false
  echo: false
---

## Setup

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(fixest)
  library(modelsummary)
  library(ggbeeswarm)
  library(knitr)
})
```

## Honesty Experiment: Qualitative Analysis

```{r}
cluster_rep_text <- read_csv(
  "../data/generated/honesty_rounds_reported_amount_reason_representative_texts.csv", show_col_types = FALSE
)

kable(cluster_rep_text, col.names = c("Cluster", "Representative text for Amount Reason"), align = c('l', 'c'))

```

```{r}
hrounds <- read_csv(
    "../data/generated/honesty_rounds_with_clusters.csv", show_col_types = FALSE
) %>%
    mutate(
        experiment = factor(ifelse(
        experiment == "fhonesty",
        "Business Framing", "Neutral Framing"
        ), c("Neutral Framing", "Business Framing")),
        slack = reported_amount - true_amount,
        truthful = as.integer(reported_amount == true_amount),
        honesty = 1 - (reported_amount - true_amount)/(6000 - true_amount)
    )

hparticipants <- read_csv(
  "../data/generated/honesty_participants.csv", show_col_types = FALSE
) %>%
  mutate(
    experiment = factor(ifelse(
      experiment == "fhonesty",
      "Business Framing", "Neutral Framing"
    ), c("Neutral Framing", "Business Framing"))
  )

hpart <- hrounds %>%
  group_by(experiment, session_code, player_id) %>%
  summarise(
    sum_honesty = 1 - sum(reported_amount - true_amount)/sum(6000 - true_amount),
    truthful = as.integer(sum_honesty == 1),
    reported_amount_reason_similarity_score_cluster_0 = mean(reported_amount_reason_similarity_score_cluster_0),
    reported_amount_reason_similarity_score_cluster_1 = mean(reported_amount_reason_similarity_score_cluster_1),
    reported_amount_reason_similarity_score_cluster_2 = mean(reported_amount_reason_similarity_score_cluster_2),
    .groups = "drop"
  ) %>% left_join(hparticipants, by = c("experiment", "session_code", "player_id")) %>%
  mutate(
    passed_cc = as.integer(comprehension_check1 == 1 & comprehension_check2 == 1),
    classified_as_human = as.integer(human_check == 1)
  )

color_scale <- RColorBrewer::brewer.pal(3 ,"Set1")[c(2, 1)]
```

### Panel A: Round Level

```{r}
datasummary(
  (`% Truthful`= truthful) + 
    (`% Honest`=honesty) +
    (`Cluster 1 - Similarity Score`=reported_amount_reason_similarity_score_cluster_0) +
    (`Cluster 2 - Similarity Score`=reported_amount_reason_similarity_score_cluster_1) +
    (`Cluster 3 - Similarity Score`=reported_amount_reason_similarity_score_cluster_2) ~ experiment*(N + Mean + SD), 
  data = hrounds,
  fmt = 7
)

chisq.test(hrounds$truthful, hrounds$experiment)
chisq.test(hrounds$truthful, hrounds$experiment)
t.test(honesty ~ experiment, data = hrounds %>% filter(honesty < 1))
t.test(reported_amount_reason_similarity_score_cluster_0 ~ experiment, data = hrounds %>% filter(honesty < 1))
t.test(reported_amount_reason_similarity_score_cluster_1 ~ experiment, data = hrounds %>% filter(honesty < 1))
t.test(reported_amount_reason_similarity_score_cluster_2 ~ experiment, data = hrounds %>% filter(honesty < 1))
wilcox.test(honesty ~ experiment, data = hrounds %>% filter(honesty < 1))

```

{{< pagebreak >}}

### Panel B: Participant Level

```{r}
datasummary(
  (`% Always Truthful`= truthful) + 
    (`% Honest`= sum_honesty) +
    (`% Passed Comprehension Checks` = passed_cc) +
    (`% Classified as Human` = classified_as_human) +
    (`Cluster 1 - Similarity Score`=reported_amount_reason_similarity_score_cluster_0) +
    (`Cluster 2 - Similarity Score`=reported_amount_reason_similarity_score_cluster_1) +
    (`Cluster 3 - Similarity Score`=reported_amount_reason_similarity_score_cluster_2) ~ experiment*(N + Mean + SD), 
  data = hpart,
  fmt = 7
)

chisq.test(hpart$truthful, hpart$experiment)
chisq.test(hpart$passed_cc, hpart$experiment)

t.test(sum_honesty ~ experiment, data = hpart %>% filter(sum_honesty < 1))
t.test(reported_amount_reason_similarity_score_cluster_0 ~ experiment, data = hrounds %>% filter(honesty < 1))
t.test(reported_amount_reason_similarity_score_cluster_1 ~ experiment, data = hrounds %>% filter(honesty < 1))
t.test(reported_amount_reason_similarity_score_cluster_2 ~ experiment, data = hrounds %>% filter(honesty < 1))
wilcox.test(sum_honesty ~ experiment, data = hpart %>% filter(sum_honesty < 1))
```

{{< pagebreak >}}


## Trust Experiment: Qualitative Analysis

```{r}
cluster_rep_text <- read_csv(
  "../data/generated/trust_rounds_sent_reason_representative_texts.csv", show_col_types = FALSE
)

kable(cluster_rep_text, col.names = c("Cluster", "Representative Text for Sent Reason"), align = c('l', 'c'))
```

```{r}
cluster_rep_text <- read_csv(
  "../data/generated/trust_rounds_sent_back_reason_representative_texts.csv", show_col_types = FALSE
)
kable(cluster_rep_text, col.names = c("Cluster", "Representative Text for Sent Back Reason"), align = c('l', 'c'))
```


```{r}
trounds <- read_csv(
  "../data/generated/trust_rounds_with_clusters.csv", show_col_types = FALSE
) %>%
  mutate(
    experiment = factor(ifelse(
      experiment == "ftrust",
      "Business Framing", "Neutral Framing"
    ), c("Neutral Framing", "Business Framing")),
    pct_returned = sent_back_amount/(3*sent_amount)
  )
```

{{< pagebreak >}}

### Panel A: Round Level


```{r}
datasummary(
    (`Amount Sent`= sent_amount) +
    (`Amount Returned`= sent_back_amount) +
    (`% Returned` = pct_returned) +
    (`Cluster 1 - Sent Similarity Score`=sent_reason_similarity_score_cluster_0) +
    (`Cluster 2 - Sent Similarity Score`=sent_reason_similarity_score_cluster_1) +
    (`Cluster 3 - Sent Similarity Score`=sent_reason_similarity_score_cluster_2) +
    (`Cluster 1 - Returned Similarity Score`=sent_back_reason_similarity_score_cluster_0) +
    (`Cluster 2 - Returned Similarity Score`=sent_back_reason_similarity_score_cluster_1) +
    (`Cluster 3 - Returned Similarity Score`=sent_back_reason_similarity_score_cluster_2) ~ experiment*(N + Mean + SD), 
  data = trounds,
  fmt = 7
)

t.test(sent_amount ~ experiment, data = trounds)
wilcox.test(sent_amount ~ experiment, data = trounds)

t.test(sent_back_amount ~ experiment, data = trounds)
wilcox.test(sent_back_amount ~ experiment, data = trounds)

t.test(pct_returned ~ experiment, data = trounds)
wilcox.test(pct_returned ~ experiment, data = trounds)

t.test(sent_reason_similarity_score_cluster_0 ~ experiment, data = trounds)
wilcox.test(sent_reason_similarity_score_cluster_0 ~ experiment, data = trounds)

t.test(sent_reason_similarity_score_cluster_1 ~ experiment, data = trounds)
wilcox.test(sent_reason_similarity_score_cluster_1 ~ experiment, data = trounds)

t.test(sent_reason_similarity_score_cluster_2 ~ experiment, data = trounds)
wilcox.test(sent_reason_similarity_score_cluster_2 ~ experiment, data = trounds)

t.test(sent_back_reason_similarity_score_cluster_0 ~ experiment, data = trounds)
wilcox.test(sent_back_reason_similarity_score_cluster_0 ~ experiment, data = trounds)

t.test(sent_back_reason_similarity_score_cluster_1 ~ experiment, data = trounds)
wilcox.test(sent_back_reason_similarity_score_cluster_1 ~ experiment, data = trounds)

t.test(sent_back_reason_similarity_score_cluster_2 ~ experiment, data = trounds)
wilcox.test(sent_back_reason_similarity_score_cluster_2 ~ experiment, data = trounds)
```

{{< pagebreak >}}

## Gift Exchange Experiment: Qualitative Analysis

```{r}
cluster_rep_text <- read_csv(
  "../data/generated/giftex_rounds_effort_reason_representative_texts.csv", show_col_types = FALSE
)
kable(cluster_rep_text, col.names = c("Cluster", "Representative Text for Effort Reason"), align = c('l', 'c'))
```

```{r}
cluster_rep_text <- read_csv(
  "../data/generated/giftex_rounds_wage_reason_representative_texts.csv", show_col_types = FALSE
)
kable(cluster_rep_text, col.names = c("Cluster", "Representative Text for Wage Reason"), align = c('l', 'c'))
```


{{< pagebreak >}}


```{r}
cost <- function(e) {
  case_when(
    e == 0.1 ~ 0,
    e == 0.2 ~ 1,
    e == 0.3 ~ 2,
    e == 0.4 ~ 4,
    e == 0.5 ~ 6,
    e == 0.6 ~ 8,
    e == 0.7 ~ 10,
    e == 0.8 ~ 12,
    e == 0.9 ~ 15,
    e == 1.0 ~ 28,
    TRUE ~ NA
  )
}

grounds <- read_csv(
  "../data/generated/giftex_rounds_with_clusters.csv", show_col_types = FALSE
) %>%
  mutate(
    experiment = factor(ifelse(
      experiment == "fgiftex",
      "Business Framing", "Neutral Framing"
    ), c("Neutral Framing", "Business Framing")),
    payoff_employer = (100 - wage)*effort,
    payoff_employee = wage - cost(effort)
  )
```

### Panel A: Round Level

```{r}
datasummary(
    (`Effort`= effort) +
    (`Cost`= cost(effort)) +
    (`Wage`= wage) +
    (`Payoff Employer`= payoff_employer) +
    (`Payoff Employee`= payoff_employee) +
    (`Cluster 1 - Effort Similarity Score`=effort_reason_similarity_score_cluster_0) +
    (`Cluster 2 - Effort Similarity Score`=effort_reason_similarity_score_cluster_1) +
    (`Cluster 3 - Effort Similarity Score`=effort_reason_similarity_score_cluster_2) +
    (`Cluster 1 - Wage Similarity Score`=wage_reason_similarity_score_cluster_0) +
    (`Cluster 2 - Wage Similarity Score`=wage_reason_similarity_score_cluster_1) +
    (`Cluster 3 - Wage Similarity Score`=wage_reason_similarity_score_cluster_2) ~ experiment*(N + Mean + SD), 
  data = grounds,
  fmt = 7
)

t.test(effort ~ experiment, data = grounds)
wilcox.test(effort ~ experiment, data = grounds)

t.test(wage ~ experiment, data = grounds)
wilcox.test(wage ~ experiment, data = grounds)

t.test(payoff_employer ~ experiment, data = grounds)
wilcox.test(payoff_employer ~ experiment, data = grounds)

t.test(payoff_employee ~ experiment, data = grounds)
wilcox.test(payoff_employee ~ experiment, data = grounds)

t.test(effort_reason_similarity_score_cluster_0 ~ experiment, data = grounds)
wilcox.test(effort_reason_similarity_score_cluster_0 ~ experiment, data = grounds)

t.test(effort_reason_similarity_score_cluster_1 ~ experiment, data = grounds)
wilcox.test(effort_reason_similarity_score_cluster_1 ~ experiment, data = grounds)

t.test(effort_reason_similarity_score_cluster_2 ~ experiment, data = grounds)
wilcox.test(effort_reason_similarity_score_cluster_2 ~ experiment, data = grounds)

t.test(wage_reason_similarity_score_cluster_0 ~ experiment, data = grounds)
wilcox.test(wage_reason_similarity_score_cluster_0 ~ experiment, data = grounds)

t.test(wage_reason_similarity_score_cluster_1 ~ experiment, data = grounds)
wilcox.test(wage_reason_similarity_score_cluster_1 ~ experiment, data = grounds)

t.test(wage_reason_similarity_score_cluster_2 ~ experiment, data = grounds)
wilcox.test(wage_reason_similarity_score_cluster_2 ~ experiment, data = grounds)
```
